### ISSUE TITLE
Build error with Compose for Web 1.4.0

### ISSUE THREAD

**Issue by joreilly** [chihsuanwu/google-maps-compose-web#5]
I'm getting following build error after upgrading to Compose for Web 1.4.0

```
java.lang.IllegalStateException: IrPropertyPublicSymbolImpl for org.jetbrains.compose.web.dom/Style|4264866761512685317[0] is already bound: PROPERTY name:Style visibility:internal modality:FINAL [val]
```

If I remove dependency on this library then it builds/runs fine.

Changes made so far are in following branch https://github.com/joreilly/PeopleInSpace/tree/compose_multiplatform_1_4

**Comment by chihsuanwu** [comment]
@joreilly I've released version 0.3.1-alpha which fixes the dependency issue. Thanks!
